blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/RecordReplay/devtools/discussions
    about: Share product feedback, feature requests, ask questions
  - name: Discord Community
    url: https://discord.gg/hw3eDwvChz
    about: Stop by if you would like to discuss Replay
