name: Nightly
on:
  push:
    branches:
      - 'main'


jobs:
  trunk_check:
    name: Trunk Check Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.0.0
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
